#!/usr/bin/env python3
import lumbercalc
import argparse

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('-P', '--prices', default='lumber.json')
    parser.add_argument('-v', '--verbose', action = 'store_true')

    args = parser.parse_args()

    lumbercalc.run(args)

